version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user213
      MYSQL_PASSWORD: user213
    ports:
      - 3012:3306

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   container_name: api
  #   ports:
  #     - 3011:3000
  #   environment:
  #     - MYSQL_HOST=mysql
  #     - MYSQL_PORT=3306
  #     - MYSQL_USER=user213
  #     - MYSQL_PASSWORD=user213
  #     - MYSQL_DATABASE=database
  #   depends_on:
  #     - mysql
  #   volumes:
  #     - .backend:/var

  adminer:
    image: adminer
    container_name: db_admin
    restart: always
    ports:
      - 3014:8080
